name: Build Cloud Flatpak
on: [push, workflow_dispatch]

jobs:
  flatpak:
    name: "Flatpak Packaging"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup Flatpak Environment & Build
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder
        sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install flathub org.freedesktop.Sdk//25.08 org.freedesktop.Platform//25.08 -y
        flatpak-builder --repo=repo --force-clean build-dir org.akashdh11.skystream.json
        flatpak build-bundle repo skystream.flatpak org.akashdh11.skystream

    - name: Upload Finished App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: SkyStream-Flatpak-Bundle
        path: skystream.flatpak
